name: velvet_recorder
description: Disguised notes + recorder app.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2

  # Audio recording
  record: ^5.0.3

  # Video recording (camera preview + video files)
  camera: ^0.11.0+2

  # Local file paths
  path_provider: ^2.1.3
  path: ^1.9.0

  # Runtime permissions
  permission_handler: ^11.3.0

  # Local database for notes + recordings metadata
  sqflite: ^2.3.3+1

  # Date formatting
  intl: ^0.19.0

  # Open audio/video with system player
  open_filex: ^4.5.0
  flutter_foreground_task: ^8.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true

dependency_overrides:
  record_linux: ^1.2.1
  record_platform_interface: ^1.4.0
